---
- name: Include variables
  gather_facts: false
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Register postgres_password
      ansible.builtin.command: "pass show ansible/postgres/sinapi"
      register: postgres_password

    - name: Add host variables
      ansible.builtin.add_host:
        name: SECRET
        postgres_password: "{{ postgres_password.stdout }}"
      tags:
        - docker

- hosts: cloud0
  vars:
    exec_file: /var/lib/sinapi/spring-boot-0.0.1-SNAPSHOT.jar
  tasks:
    - name: Ensure group web exists
      ansible.builtin.group:
        name: web
        state: present
      become: yes

    - name: Create user for service
      ansible.builtin.user:
        name: sinapi
        groups: 
          - web
        append: yes
      become: yes

    - name: Create config directory
      ansible.builtin.file:
        path: "/var/lib/sinapi"
        state: directory
        mode: '0770'
        owner: sinapi
        group: web
      become: yes

    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/alexmalder/sinapi'
        dest: "{{ ansible_env.HOME }}/sinapi"
        version: master
        force: yes

    - name: Build with gradle
      ansible.builtin.command: 
        chdir: "{{ ansible_env.HOME }}/sinapi"
        cmd: gradle build

    - name: Move jar to /var/lib/sinapi
      copy:
        src: "{{ ansible_env.HOME }}/sinapi/build/libs/spring-boot-0.0.1-SNAPSHOT.jar"
        dest: "{{ exec_file }}"
        remote_src: yes

    - name: Push service
      ansible.builtin.template:
        src: ".ansible/sinapi.service"
        dest: "/usr/lib/systemd/system/sinapi.service"
        mode: '0640'
      become: yes

    - name: Setup service
      ansible.builtin.systemd:
        name: sinapi
        state: restarted
        enabled: true
        daemon_reload: true
      become: yes
